export enum Auth {
    "RUMMY.PLAY" = "RUMMY.PLAY",
    "RUMMY.CREATE.LOBBY" = "RUMMY.CREATE.LOBBY",
    "RUMMY.JOIN.LOBBY" = "RUMMY.JOIN.LOBBY",
    "RUMMY.DELETE.LOBBY" = "RUMMY.DELETE.LOBBY",
    "RUMMY.START.GAME" = "RUMMY.START.GAME",
    "RUMMY.END.GAME" = "RUMMY.END.GAME",
    "RUMMY.WATCH.GAME" = "RUMMY.WATCH.GAME",
    "RUMMY.CHAT" = "RUMMY.CHAT",
    "RUMMY.KICK.LOBBY" = "RUMMY.KICK",
    "PLAYER.UPDATE.YOURSELF" = "PLAYER.UPDATE.YOURSELF",
    "PLAYER.DELETE.YOURSELF" = "PLAYER.DELETE.YOURSELF",
    "PLAYER.GET.INFO" = "PLAYER.GET.INFO",
    "PLAYER.CREATE" = "PLAYER.CREATE",
    "PLAYER.UPDATE" = "PLAYER.UPDATE",
    "PLAYER.DELETE" = "PLAYER.DELETE",
    "PLAYER.GET.ALL" = "PLAYER.GET.ALL",

}